name: poultry
description: A new Flutter project.
publish_to: 'none' # Keep this for private packages

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2  # State management library
  http: ^0.13.5  # Networking library
  url_launcher: 6.3.0  # For launching URLs
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4  # Firebase Firestore
  firebase_auth: ^5.3.1  # Firebase Authentication
  firebase_core: ^3.4.0  # Firebase Core
  google_fonts: ^6.2.1  # Google Fonts
  image_picker: ^1.1.2  # Image Picker
  shared_preferences: 2.2.2  # Local storage
  sqflite: ^2.3.3+2  # SQLite database

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # For recommended lints

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

