name: poultry
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  cloud_firestore_platform_interface: ^6.4.0
  cloud_firestore_web: ^4.2.0
  collection: 1.17.2 # Downgraded to match flutter_test
  dropdown_button2: 2.3.9
  easy_debounce: ^2.0.3
  file_picker: ^8.1.2
  firebase_auth: ^5.3.1
  firebase_auth_platform_interface: ^7.4.4
  firebase_auth_web: ^5.12.6
  firebase_core: ^3.4.0
  firebase_core_platform_interface: ^5.3.0
  firebase_core_web: ^2.17.5
  firebase_performance: ^0.10.0+5
  firebase_performance_platform_interface: ^0.1.4+41
  firebase_performance_web: ^0.1.6+13
  firebase_storage: ^12.2.0
  firebase_storage_platform_interface: ^5.1.28
  firebase_storage_web: ^3.9.13
  flutter_animate: 4.5.0
  flutter_cache_manager: ^3.4.1
  flutter_facebook_auth: ^7.1.0
  flutter_plugin_android_lifecycle: ^2.0.22
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: 0.7.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.1.30
  google_sign_in_ios: ^5.7.7
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4+2
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+13
  image_picker_for_web: ^3.0.5
  image_picker_ios: ^0.8.12
  image_picker_platform_interface: ^2.10.0
  intl: 0.19.0
  json_path: ^0.7.4
  mime_type: ^1.0.1
  page_transition: 2.1.0
  path_provider: ^2.1.4
  path_provider_android: ^2.2.10
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  percent_indicator: ^4.2.3
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  rxdart: ^0.28.0
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: ^6.1.3
  sign_in_with_apple_platform_interface: ^1.1.0
  sign_in_with_apple_web: ^2.1.0
  simple_gradient_text: ^1.3.0
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.3.3+2
  stream_transform: 2.1.0
  timeago: ^3.7.0
  url_launcher: 6.2.0  
  url_launcher_android: ^6.2.0
  url_launcher_ios: 6.2.0
  url_launcher_platform_interface: 2.3.2
  video_player: ^2.7.0
  video_player_android: ^2.7.5
  video_player_avfoundation: 2.5.0
  video_player_platform_interface: 6.2.2
  video_player_web: ^2.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.5
  image: ^4.2.0
  lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'
  adaptive_icon_background: '#00000000'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
