name: poultry
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0  # Downgraded to avoid conflicts
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.4.0
  firebase_performance: ^0.10.0+5
  firebase_storage: ^12.2.0
  flutter_animate: 4.5.0
  flutter_cache_manager: ^3.4.1
  flutter_facebook_auth: ^7.1.0
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: 0.19.0
  provider: 6.1.2
  shared_preferences: 2.2.2
  url_launcher: 6.3.0
  video_player: ^2.9.1
  cupertino_icons: ^1.0.0

dependency_overrides:
  web: 0.1.4-beta  # Matching flutter_test’s pinned version
  http: 1.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.png'
  adaptive_icon_background: '#00000000'
  adaptive_icon_foreground: 'assets/images/adaptive_foreground_icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
