name: Flutter CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-arm64
      PUB_CACHE: /Users/runner/.pub-cache

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Use the stable version of Flutter

      - name: Clean Flutter Cache
        run: flutter pub cache repair

      - name: Get Dependencies
        run: |
          flutter pub get
        env:
          PUB_ENVIRONMENT: ci

      - name: Fix Pod Issues (iOS only)
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          flutter pub get  # Ensures the required xcconfig is generated
          pod install

      - name: Run Flutter Tests
        run: flutter test --no-pub

      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
