name: Flutter iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Flutter environment
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Pre-cache iOS artifacts (important step)
      - name: Pre-cache iOS artifacts
        run: flutter precache --ios

      # Clean the Flutter project to avoid conflicts
      - name: Clean project
        run: flutter clean

      # Set up CocoaPods environment
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update

      # Install pods for the iOS project
      - name: Install iOS Pods
        working-directory: ios
        run: |
          rm -rf Pods Podfile.lock
          pod install

      # Build the iOS app in release mode
      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      # Verify Flutter installation (optional step for debugging)
      - name: Flutter doctor
        run: flutter doctor
