name: Build iOS IPA

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up Flutter environment
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    # 3. Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # 4. Update Podfile to ensure Firebase version compatibility
    - name: Update Podfile
      run: |
        sed -i '' "s|:git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.25.0'|\'Firebase/Firestore\', '11.2.0'|" ios/Podfile

    # 5. Clean Pod cache and install pods
    - name: Clean Pod cache and install
      run: |
        cd ios
        rm -rf Podfile.lock Pods
        pod cache clean --all
        pod install --repo-update

    # 6. Build iOS IPA without code signing
    - name: Build iOS IPA
      run: flutter build ios --release --no-codesign

    # 7. Upload IPA as a build artifact
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: app-release.ipa
        path: build/ios/iphoneos/*.ipa
