# .github/workflows/ios-ipa-build.yaml
name: Build iOS IPA

on: 
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          flutter clean  # Ensure previous artifacts are removed
          flutter pub get

      - name: Install CocoaPods Dependencies
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS Release (Unsigned)
        run: |
          flutter build ios --release --no-codesign  # Skip signing

      - name: Prepare IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r FlutterApp.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlutterApp
          path: build/ios/iphoneos/FlutterApp.ipa
